name = "Trale"
version = "0.1.0"
defaultTargets = ["Trale"]
# lintDriver = "batteries/runLinter"
testDriver = "TraleTest"

[[lean_lib]]
name = "Trale"

[[lean_lib]]
name = "TraleTest"
globs = ["TraleTest.+"]

[[require]]
name = "Qq"
scope = "leanprover-community"

# Mathlib is only required for TraleTest.
[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "aesop"
scope = "leanprover-community"

