name = "Trale"
version = "0.1.0"
defaultTargets = ["trale"]
lintDriver = "batteries/runLinter"
testDriver = "TraleTest"

[[lean_lib]]
name = "Trale"

[[lean_lib]]
name = "TraleTest"
globs = ["TraleTest.+"]

[[lean_exe]]
name = "trale"
root = "Main"

[[require]]
name = "Qq"
scope = "leanprover-community"

[[require]]
name = "mathlib"
scope = "leanprover-community"
